[package]
name = "coyotes"
version = "0.1.0"
edition = "2024"
license = "BSD-3-Clause"
license_file = "LICENCE"
repository = "https://github.com/w-lfpup/coyote-rs"
readme = "README.md"
keywords = ["html", "template", "templates"]
categories = ["template-engine"]